### ISSUE TITLE
ReferenceError: fs is not defined error

### ISSUE THREAD

**Issue by xyzbilal** [Snirpo/node-vad#6]
I installed package vie npm.  while trying to run my app getting this error. 
my package.json is like

> 
{
>     "private": true,
>     "scripts": {
>         "dev": "npm run development",
>         "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
>         "watch": "npm run development -- --watch",
>         "watch-poll": "npm run watch -- --watch-poll",
>         "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
>         "prod": "npm run production",
>         "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
>     },
>     "devDependencies": {
>         "axios": "^0.19",
>         "cross-env": "^7.0",
>         "laravel-mix": "^5.0.1",
>         "lodash": "^4.17.13",
>         "resolve-url-loader": "^3.1.0",
>         "sass": "^1.15.2",
>         "sass-loader": "^8.0.0",
>         "vue-template-compiler": "^2.6.11"
>     },
>     "dependencies": {
>         "bindings": "^1.5.0",
>         "fs": "0.0.1-security",
>         "nan": "^2.14.0",
>         "node-vad": "^1.1.4",
>         "util-promisifyall": "^1.0.6",
>         "voice-activity-detection": "0.0.5",
>         "vue": "^2.1.10"
>     }
> }

I tried to run code chunk is in [https://npm.runkit.com/node-vad](https://npm.runkit.com/node-vad) but its also gives same error. is there any solution for this situation?

**Comment by Snirpo** [comment]
Hi, I do see you're adding your own "fs": "0.0.1-security" dependency. You could try to remove that. Nodejs has the fs module built-in. node-vad itself isn't using fs.

I also see you're adding Vue as a dependency, which is for browser apps. You cannot use this library in browser apps. It's only for backend apps. That's why it's called **node-**vad :)
